# Utilise l’image officielle Nginx légère
FROM nginx:alpine

# Copie tout le contenu du dossier frontend dans le dossier de base nginx
COPY . /usr/share/nginx/html

# Expose le port 80 (par défaut pour nginx)
EXPOSE 80

# Le serveur nginx démarre automatiquement
